apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: phase2-scaledobject
  namespace: sdtd
spec:
  scaleTargetRef:
    name: phase2
  pollingInterval: 10
  maxReplicaCount:  25
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-svc.sdtd:9092
      consumerGroup: my-group
      topic: phase1
      lagThreshold: "15"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: phase3-scaledobject
  namespace: sdtd
spec:
  scaleTargetRef:
    name: phase3
  pollingInterval: 10
  maxReplicaCount:  25
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-svc.sdtd:9092
      consumerGroup: my-group
      topic: phase3
      lagThreshold: "15"
