apiVersion: v1
kind: ServiceAccount
metadata:
  name: phase1-deployer
  namespace: sdtd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sdtd
  name: phase1-deployer
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: phase1-deployer
  namespace: sdtd
subjects:
- kind: ServiceAccount
  name: phase1-deployer
  namespace: sdtd
roleRef:
  kind: Role
  name: phase1-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phase1-deployer
  name: phase1-deployer
  namespace: sdtd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phase1-deployer
  template:
    metadata:
      labels:
        app: phase1-deployer
    spec:
      serviceAccountName: phase1-deployer
      containers:
        - image: ilisius/deployment_phase1
          imagePullPolicy: Always
          name: phase1-deployer
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: phase1-deployer
  namespace: sdtd
spec:
  selector:
    app: phase1-deployer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: phase1-deployer
  namespace: sdtd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`phase1.sdtd.marche.ovh`)
      kind: Rule
      services:
        - name: phase1-deployer
          port: 80